### ISSUE TITLE
luci-app-natmap这个不兼容op

### ISSUE THREAD

**Issue by remember19890604** [heiher/natmap#14]
安装后不显示界面

**Comment by heiher** [comment]
luci-app-natmap目前支持官方版本的OpenWrt 22.03及之后版本，请问在哪个具体版本的系统上发现不兼容问题？

**Comment by ysc3839** [comment]
安装后尝试按Ctrl+F5重新加载页面？也可以试试清除浏览器缓存，以及重启OpenWrt。

**Comment by zhezhe168** [comment]
> luci-app-natmap目前支持官方版本的OpenWrt 22.03及之后版本，请问在哪个具体版本的系统上发现不兼容问题？


LuCI Master (git-22.279.28429-0cb5c5c)

这个版本的

**Comment by ysc3839** [comment]
@zhezhe168 这个版本号唯一有效的信息是 commit hash `0cb5c5c`。不过我去搜了下找到了对应仓库 https://github.com/coolsnowwolf/luci/tree/0cb5c5c78274871cd98c3e114ed9e70ab86ad5d6 这个应该是没支持前端渲染，所以用不了。有空我加上旧版本的支持吧。

**Comment by zhezhe168** [comment]
好的，谢谢大佬

**Comment by ChuLiqiang** [comment]
相同的问题装了不显示:
git-22.355.73286-1a4ac92
![image](https://user-images.githubusercontent.com/2747722/216769192-b08c9750-9676-4371-81d9-51d86c2071ed.png)
![image](https://user-images.githubusercontent.com/2747722/216769207-5cc85776-d888-4497-ab83-5965d33efe9a.png)

**Comment by ChuLiqiang** [comment]
> @zhezhe168 这个版本号唯一有效的信息是 commit hash `0cb5c5c`。不过我去搜了下找到了对应仓库 https://github.com/coolsnowwolf/luci/tree/0cb5c5c78274871cd98c3e114ed9e70ab86ad5d6 这个应该是没支持前端渲染，所以用不了。有空我加上旧版本的支持吧。

能帮忙看下咋弄吗?

**Comment by heiher** [comment]
> 能帮忙看下咋弄吗?

图形界面需要增加旧版OpenWrt支持才行，先用命令行方式吧，也很简单的。

**Comment by tsui603** [comment]
我也是旧版本 LuCI Master (git-22.190.54720-e2af321)，求支持旧版本，谢谢！

> @zhezhe168 这个版本号唯一有效的信息是 commit hash `0cb5c5c`。不过我去搜了下找到了对应仓库 https://github.com/coolsnowwolf/luci/tree/0cb5c5c78274871cd98c3e114ed9e70ab86ad5d6 这个应该是没支持前端渲染，所以用不了。有空我加上旧版本的支持吧。

**Comment by jeremysun0324** [comment]
LuCI Master (git-23.177.50322-72213cf) 同样的问题

**Comment by microyin715** [comment]
QWRT R23.11.11 / LuCI Master (git-23.305.37706-43242b7) 安装了也不显示
