### ISSUE TITLE
怎样在FreeBSD上编译？

### ISSUE THREAD

**Issue by Alex6357** [heiher/natmap#16]
FreeBSD 13.1-RELEASE使用gmake编译之后运行文件报错：
`[E] hev_sock_client_tcp src/hev-sock.c:152`
`[E] tnsk_run src/hev-tnsk.c:93`

**Comment by heiher** [comment]
从错误信息看是因为端口重用(reuseport)失败，导致不能侦听，应该是使用的natmap bind mode吧，在FreeBSD上没有像Linux一样的跨进程打开端口重用的功能，所以请使用forward mode试试吧，指定 -t 和 -p 参数。

**Comment by Alex6357** [comment]
已经成功，非常感谢
