### ISSUE TITLE
命令行以及luci均报错无法使用

### ISSUE THREAD

**Issue by cctv4-cgtn** [heiher/natmap#17]
运行在openwrt主路由上
使用命令natmap -s stun.stunprotocol.org -h qq.com -b 5665
[E] hev_sock_client_stun src/hev-sock.c:281
[E] task_entry src/hev-stun.c:289
[E] hev_sock_client_tcp src/hev-sock.c:167
[E] tnsk_run src/hev-tnsk.c:93
luci界面按示例图片配置后错误相同
麻烦看看是哪里的问题
同时麻烦详细说明一下配置Cloudflare api的文件这两个变量${RULE}和${RECORD}应该如何填写，谢谢

**Comment by heiher** [comment]
昨天开始 stun.stunprotocol.org 服务down了，试试用 stun.voip.blackberry.com

RECORD是cloudflare创建的dns记录对应的id，从web页面的json中获取，RULE是源站规则的id，获取方法类似。

**Comment by cctv4-cgtn** [comment]
已解决，谢谢
