### ISSUE TITLE
使用-4参数指定的情况下绑定端口，绑定到了ipv6地址上，给ipv4分配了新的端口

### ISSUE THREAD

**Issue by 2775668948** [heiher/natmap#19]
在同时有ipv4和ipv6的情况下使用-4参数指定，指定绑定端口，未能成功绑定到ipv4地址上。
使用命令
 ```natmap -4 -s stun.sipnet.com -h qq.com -b 53277 -t 192.168.2.201 -p 53766``
结果
ipv4 28894 ipv6 53277

**Comment by heiher** [comment]
这就是正常的行为，ipv4设备端没有直接分配公网IP地址，运营商的NAT映射后分配的公网端口为28894(28894指向内网的53277)，而ipv6是直接公网，所以端口与程序(-b)绑定的端口相同为53277。

**Comment by 2775668948** [comment]
理解了，感谢
