### ISSUE TITLE
[Feature Request] UPnP Server

### ISSUE THREAD

**Issue by rankaiyx** [heiher/natmap#20]
Add upnp function to the router so that port mapping can be completed automatically.
This should be an exciting feature.

**Comment by heiher** [comment]
Is possible to do this in hook script? add port mapping rule by call upnp client util (e.g. miniupnpc).

**Comment by rankaiyx** [comment]
Both methods can do this by plug-in or by integrating a upnp server.
We can try both methods and see which is easier to implement.

**Comment by rankaiyx** [comment]
I found a upnp project that may be of reference value.
https://github.com/ofekp/TinyUPnP

**Comment by rankaiyx** [comment]
https://github.com/easion/tinynatpmpd

**Comment by rankaiyx** [comment]
https://www.rfc-editor.org/rfc/rfc6886.html

"Correspondingly, NAT-PMP allows a client to request a desired external port, and if that external port is already in use by some other client, the NAT-PMP server will instead assign some other available external port. UPnP IGD does not do this. "

This gives us the opportunity to return the actual external port to the client.

**Comment by OpportunityLiu** [comment]
I've made a simple implementation with nodejs.

https://github.com/OpportunityLiu/nat-mapmp

**Comment by rankaiyx** [comment]
> I've made a simple implementation with nodejs.
> 
> https://github.com/OpportunityLiu/nat-mapmp
Great! We need a usage document.

**Comment by OpportunityLiu** [comment]
> Great! We need a usage document.

I've added readme and releases. You can also use `nat-mapmp --help` to see all options.

![image](https://github.com/heiher/natmap/assets/13471233/f7dd587f-84ce-436d-867d-90482875eef1)

![image](https://github.com/heiher/natmap/assets/13471233/96aa8d41-8d29-40b0-9c73-36d0a0959752)

**Comment by OpportunityLiu** [comment]
> https://www.rfc-editor.org/rfc/rfc6886.html
> 
> "Correspondingly, NAT-PMP allows a client to request a desired external port, and if that external port is already in use by some other client, the NAT-PMP server will instead assign some other available external port. UPnP IGD does not do this. "
> 
> This gives us the opportunity to return the actual external port to the client.

Basically, run UPnP IGD server behind NAT is impossible, as well as PCP with PREFER_FAILURE support (which is designed for working with IGD, see https://datatracker.ietf.org/doc/html/rfc6887#section-13.2)
