### ISSUE TITLE
[E] hev_exec_run src/hev-exec.c:90 似乎无法调用通知脚本

### ISSUE THREAD

**Issue by Xecuss** [heiher/natmap#22]
openwrt/lede 似乎无法正常调用通知脚本，不带脚本参数一切正常，加上就会报错，版本号和命令如下图

![image](https://user-images.githubusercontent.com/16537413/223450581-5ab44f44-3b44-4b4c-ab25-1082c2d007bc.png)

**Comment by heiher** [comment]
脚本第一行写上:

```bash
#!/bin/sh
```

**Comment by Xecuss** [comment]
> 脚本第一行写上:
> 
> ```shell
> #!/bin/sh
> ```

不好意思，确实是这个问题。主要一开始试的时候确实是带了这个的但是似乎因为别的什么原因没成功，后来用简化的脚本这个又没加上所以以为有问题了。
