### ISSUE TITLE
udp模式下断线重连后貌似不能调用更新脚本

### ISSUE THREAD

**Issue by kwxiaozhu** [heiher/natmap#3]
使用了很多天，功能正常，非常稳定，但貌似有个小问题：
udp模式下断线重连后貌似不能调用更新脚本
我开了两个转发，一个tcp，一个udp，当pppoe拨号断线重连后，tcp模式下能正常调用更新脚本更新IP，udp模式下不能正常调用脚本。
![image](https://user-images.githubusercontent.com/7983147/201237014-09be8bca-d615-4982-92be-2a07123fb77c.png)
上图两个，上面tcp是断线重连后自动调用的日志，下面udp的是我发现不能自动更新后手动杀掉进程重新运行后更新的日志

**Comment by heiher** [comment]
感谢反馈~ UDP我这不用，没能及时发现问题。刚尝试进行了修复，自测正常，请再确认:

https://github.com/heiher/natmap/releases/tag/20221111

**Comment by kwxiaozhu** [comment]
> 感谢反馈~ UDP我这不用，没能及时发现问题。刚尝试进行了修复，自测正常，请再确认:
> 
> https://github.com/heiher/natmap/releases/tag/20221111

已经正常，感谢修复！
