### ISSUE TITLE
建议支持指定服务器端口

### ISSUE THREAD

**Issue by ArchGuyWu** [heiher/natmap#30]
希望可以指定服务器的端口

**Comment by heiher** [comment]
指定STUN服务器的端口？

**Comment by ArchGuyWu** [comment]
> 指定STUN服务器的端口？

是的

**Comment by ArchGuyWu** [comment]
另外，可以的话希望也能支持指定http服务器的端口

**Comment by ArchGuyWu** [comment]
@heiher 我找到了您硬编码的两个地方：https://github.com/search?q=repo%3Aheiher%2Fnatmap+3478&type=code https://github.com/search?q=repo%3Aheiher%2Fnatmap%2080&type=code ，说实话我的需求有点过于小众了，因为所在网络环境受限才有这需求，我打算自己fork改下，那您还打算添加这个功能吗？不打算的话我就关掉这个issue

**Comment by heiher** [comment]
我都可以，或许你再多改一些增加两组参数支持可配置，并通过Pull request合入过来？

**Comment by ArchGuyWu** [comment]
可以，不过我不太会C，可能得等几天

**Comment by heiher** [comment]
没关系，你先满足你的需求，其它的可以慢慢改。

**Comment by ArchGuyWu** [comment]
> 没关系，你先满足你的需求，其它的可以慢慢改。

好的

**Comment by heiher** [comment]
还没实现。可以用公共标准端口的stun服务的。
