### ISSUE TITLE
是不是可以用域名的TXT记录存端口

### ISSUE THREAD

**Issue by Taygetus** [heiher/natmap#31]
ip4p模式在纯ipv4的网络好像解析不到，用A记录存ipv4地址，TXT记录存端口，用同一个域名

**Comment by heiher** [comment]
不排除某些网络环境的DNS服务器禁止了AAAA解析，不过我这使用正常。

当初使用AAAA记录的方式是考虑到只做一次域名解析，使用体验上会好一些，因为动态域名解析为了时效性，缓存时间一般比较短，查询延迟敏感。

目前并不妨碍其它方式的使用，只要在通知脚本中实现一下A记录存IPv4地址，TXT记录存端口。

**Comment by Taygetus** [comment]
TXT记录已经可以搞定

**Comment by lmq8267** [comment]
txt记录是可以解析IP:端口的   只需要解析一次即可  nslookup -type=txt 域名  就能获取txt记录       将natmap生成的ip和端口    以IP:端口的方式解析到域名txt记录
