### ISSUE TITLE
启动服务失败

### ISSUE THREAD

**Issue by zhangbaichang** [heiher/natmap#33]
尝试在kali和centos7上运行，发生同样报错：
[E] hev_sock_client_tcp src/hev-sock.c:152 Permission denied
[E] tnsk_run src/hev-tnsk.c:103 Start TCP keep-alive service failed.
看起来是文件夹权限不足，但是我下载的是编译好的单个文件

**Comment by heiher** [comment]
如果 `-b` 绑定的端口小于 1024，需要使用 root 用户运行，或给程序增加cap_net_bind_service。

**Comment by zhangbaichang** [comment]
使用root运行后，提示以下报错：
[E] tnsk_run src/hev-tnsk.c:152 Start STUN service failed.

**Comment by zhangbaichang** [comment]
添加cap_net_bind_service或root运行后，提示以下报错：
[E] hev_sock_client_stun src/hev-sock.c:288
[E] task_entry src/hev-stun.c:292 Start STUN service failed.

**Comment by heiher** [comment]
完整的命令贴出来看看

**Comment by zhangbaichang** [comment]
natmap -s stun.stunprotocol.org -h qq.com -b 80

**Comment by heiher** [comment]
`stun.stunprotocol.org` -> `stunserver.stunprotocol.org`

**Comment by zhangbaichang** [comment]
感激不尽，已解决
