### ISSUE TITLE
外部的端口不固定理论上是会变的，怎么处理

### ISSUE THREAD

**Issue by simplove** [heiher/natmap#36]
比如这次打洞成功以后，外部端口是5000
在公网IP发生变化以后，可能那个公网下的5000端口被人占用了，那又会重新分配端口
或者是openwrt在重启之后，端口也可能会发生变化
有没有办法用自动化的程序去获取这个端口号？

我提供一些思路：
用一些支持tcp检测的服务实时检测是不是通的，如果不通就发推送告警到企业微信或者是邮件（139邮箱）免费的短信提醒
然后人工登录openwrt查看新的端口号
可是又迎来新的问题，如果我做的是ftp服务器，那岂不是要在每个客户端上面都更改成新的端口号？
问题是frp都中断了，远程不了客户端，如何修改。。。用zerotier做为备用方案，通过zerotier登录到frp客户端，再修改？
头大。。。

**Comment by heiher** [comment]
文档：https://github.com/heiher/natmap/wiki
