### ISSUE TITLE
请教连接问题

### ISSUE THREAD

**Issue by egg1234** [heiher/natmap#37]
出口路由器是家庭路由器netgear，路由器wan口有公网ip地址，经过NatTypeTester测试是fullcone状态

在内网ubuntu 20系统上使用root用户运行下面的命令

./natmap -s stun.voip.blackberry.com -h qq.com -b 19999 -t 10.0.0.59 -p 80
或
./natmap -s stun.voip.blackberry.com -h qq.com -b 19999 -t 127.0.0.1 -p 80

输出下面信息，而且1.2.3.4的确也是路由器wan口现在的公网ip地址
1.2.3.4 19999 2001::4e1f:d848:d8ba 19999 tcp 10.0.0.59

并且这台ubuntu 20(10.0.0.59)已经安装nginx并监听80端口，内网其他机器可以直接用浏览器访问http://10.0.0.59:80，能够显示正常的web页面

然后使用外网其他机器的浏览器访问natmap输出的公网地址及端口，浏览器报告连接失败

然后在外网其他ubuntu 20机器使用nc测试natmap输出的公网地址及端口
./nc -vz 1.2.3.4 19999

输出下面的结果
nc: connect to 1.2.3.4 port 19999 (tcp) failed: Connection refused

也试过把10.0.0.59机器放到路由器的DMZ区域，情况一样，都是不能访问

想请教一下这个问题出现在什么地方？

非常感谢！

**Comment by heiher** [comment]
看上去应该是没有放行入站，参考OpenWrt的配置是： https://github.com/heiher/natmap/wiki/web#4-%E9%98%B2%E7%81%AB%E5%A2%99%E6%94%BE%E8%A1%8Ctcp%E5%8D%8F%E8%AE%AE%E7%9B%AE%E7%9A%84%E7%AB%AF%E5%8F%A36336%E7%9A%84%E5%85%A5%E7%AB%99

另外，有公网IP为何要用natmap?

**Comment by heiher** [comment]
先检查路由器wan口的入站，比如先用nc测一下，然后再抓包排查一下。不清楚什么场景，上游设备有没有可能有防火墙？

**Comment by heiher** [comment]
因为wan口是公网ip呀，如果natmap是跑在路由器上，这就是必然的结果，而如果是跑在子网主机上，也有很大概率分配相同的端口（与NAT实现相关）。

**Comment by heiher** [comment]
好吧，这看上去端口是通的，很可能是运营商阻断了HTTP协议，相同外部端口试试转发SSH或其它协议。

**Comment by heiher** [comment]
这看上去还是端口不通呀，路由器上对wan口抓包看看双向流量情况。
