### ISSUE TITLE
UDP不能绑定服务端口

### ISSUE THREAD

**Issue by xbins7210** [heiher/natmap#38]
UDP不能绑定服务端口，只能绑定空闲端口。通过iptables的nat端口映射测试失败。只能通过socat做socket层面的转发。希望后续版本能够解决此问题。

**Comment by heiher** [comment]
内核版本是多少？绑定服务端口报什么错？natmap也支持应用内转发。

**Comment by xbins7210** [comment]
> 内核版本是多少？绑定服务端口报什么错？natmap也支持应用内转发。

Alma Linux 9.2  内核版本：5.14.0-284.25.1.el9_2.x86_64
绑定的时候提示如下：
[root@localhost ~]# natmap-linux-x86_64 -u -s stun.qq.com -b 52800
[E] hev_sock_client_udp src/hev-sock.c:216 Address in use
[E] unsk_run src/hev-unsk.c:71 Start UDP keep-alive service failed.
[E] hev_sock_client_udp src/hev-sock.c:216 Address in use
[E] unsk_run src/hev-unsk.c:71 Start UDP keep-alive service failed.
[E] hev_sock_client_udp src/hev-sock.c:216 Address in use
[E] unsk_run src/hev-unsk.c:71 Start UDP keep-alive service failed.

**Comment by xbins7210** [comment]
52800端口是WireGuard端口

**Comment by heiher** [comment]
那就是内核持有的，这的确不支持。

**Comment by xbins7210** [comment]
WG算是内核持有的端口吧，那是不是如果是openvpn之类的就不存在此类问题了？

**Comment by heiher** [comment]
内核版本大于等于5.6，用户空间进程持有的端口，并且natmap有权限的情况下应该可以。

**Comment by xbins7210** [comment]
感谢大佬的耐心解答，干杯~~~
