### ISSUE TITLE
咨询一下启动以后有没有日志记录外网ip和端口？

### ISSUE THREAD

**Issue by rangdengdashi** [heiher/natmap#40]
咨询一下启动以后有没有日志记录外网ip和端口？

**Comment by heiher** [comment]
有，会通过标准输出打印出来。

**Comment by rangdengdashi** [comment]
有没有持久化的记录？没有的话只能通过重定向了

**Comment by heiher** [comment]
重定向或使用通知脚本写出。

**Comment by rangdengdashi** [comment]
通知脚本是怎么工作的？我应该如何实现用通知脚本打印ip和port？没找到相关资料

**Comment by heiher** [comment]
程序-e参数指定通知脚本的路径，获取到公网地址和端口后，调用脚本并通过参数传递给脚本，参数列表的含意见README。
