### ISSUE TITLE
问一个非常弱智的问题

### ISSUE THREAD

**Issue by calfolou** [heiher/natmap#44]
打洞成功了，通过 ip+端口也能访问到内网的服务！
然后我使用 cloudflare 做了 dns 和 origin 规则之后，直接使用域名是不能访问的。
通过nslookup 看解析结果也是正常的。
这种我直接通过域名不加端口的方式不能访问是不是因为我的域名没有备案啊？
如果是的话，请问有没有什么办法让我用域名+固定端口来访问呢？
感谢大佬

**Comment by heiher** [comment]
与备案无关，不需要备案。检查DNS解析与Origin规则设置是否正确，以及Cloudflare访问你的网络的可达性问题。

**Comment by calfolou** [comment]
我试了一下，咱们的脚本里面做 dns 解析的是没有开启代理的。
我把 dns 解析的代理打开后，这个就可以生效，但是如果不打开就不行，这个是我设置的问题还是本来就是这样呢？我查了下好像说是要启用 origin 规则是需要开启 CF 代理才生效的？是这样吗？

**Comment by heiher** [comment]
是的，需要开启代理。

**Comment by calfolou** [comment]
非常感谢～～问题解决了！
另外问一下，一次只能实现一个端口开放吗？如果我要开放多个端口，只能通过多开natmap 吗？

**Comment by heiher** [comment]
好的，多端口多开就行了。
