### ISSUE TITLE
Origin rule无法完成

### ISSUE THREAD

**Issue by hetaozhen** [heiher/natmap#48]
刚编译的，openwrt系统![image](https://github.com/heiher/natmap/assets/863637/81912ad3-4a5a-4e04-bc48-48b6c8844ef5)，DNS代码执行正常，origin rule代码无法完成，在网站上看无修改。

**Comment by heiher** [comment]
将输出重定位到 /dev/null 移除掉看看出了什么错误，如果是Auth错误的话，确认一下 API Token 是否包含对Origin rules操作的权限。

**Comment by hetaozhen** [comment]
> 将输出重定位到 /dev/null 移除掉看看出了什么错误，如果是Auth错误的话，确认一下 API Token 是否包含对Origin rules操作的权限。

CloudFlare API的Origin Rules权限开了，返回这个无效的‘m’
![屏幕截图 2024-02-26 154010](https://github.com/heiher/natmap/assets/863637/34de91ac-2614-4772-ba93-b5eaa97b060f)
![屏幕截图 2024-02-26 162414](https://github.com/heiher/natmap/assets/863637/7a741257-9fac-4b52-aeaa-273f1518c61f)

**Comment by heiher** [comment]
Sorry，是一个转义的Typo导致的：

```
\"expression\":\"(http.host eq \"${DOMAIN}\")\"
```

改为

```
\"expression\":\"(http.host eq \\\"${DOMAIN}\\\")\"
```

**Comment by hetaozhen** [comment]
起作用了，谢谢

> Sorry，是一个转义的Typo导致的：
> 
> ```
> \"expression\":\"(http.host eq \"${DOMAIN}\")\"
> ```
> 
> 改为
> 
> ```
> \"expression\":\"(http.host eq \\\"${DOMAIN}\\\")\"
> ```
