### ISSUE TITLE
tcp和udp能否共存？

### ISSUE THREAD

**Issue by doyoman** [heiher/natmap#53]
看到wiki写的，支持tcp和udp协议，默认是tcp，启用-u参数时，是udp协议，那么能否tcp和udp共存呢？

**Comment by heiher** [comment]
可以运行两个实例，一个tcp，另一个udp。

**Comment by doyoman** [comment]
这样的话，就是两个不同的外部端口吧？

**Comment by MikeWang000000** [comment]
没有办法做到端口号保持相同的。CGNAT一般会分开映射。这个我们没有办法控制。

**Comment by doyoman** [comment]
在使用vpn节点连回家的情况下，节点只能设置一个端口，那么节点要么用tcp，要么用udp么

**Comment by MikeWang000000** [comment]
看你采用什么样类型的 VPN。比如 Wireguard 只有 UDP。OpenVPN 使用 TCP 的时候也用不到 UDP。

**Comment by doyoman** [comment]
是ss节点

**Comment by MikeWang000000** [comment]
ss 只有很少的实现支持 udp-over-tcp。
推荐使用vmess协议。
