### ISSUE TITLE
网络变动后故障

### ISSUE THREAD

**Issue by dmserver** [heiher/natmap#57]
系统是armbian
正常不安装 netbird tailscale zerotier 的情况下是没有任何问题的 是否捆绑网口都能正常启动
但是安装这三个软件后 启动就会报错  而且 多次重装系统 都是这个情况
如果可以的话 能列出软件依赖 或环境修复工具 就好了  因为这个问题实在是无法避免
root@arm:/natmap_make/natmap-20240409-next# make
BUILD src/hev-conf.c
BUILD src/hev-sock.c
BUILD src/hev-main.c
BUILD src/hev-ufwd.c
BUILD src/hev-misc.c
BUILD src/hev-exec.c
BUILD src/hev-tfwd.c
BUILD src/hev-tnsk.c
BUILD src/hev-stun.c
BUILD src/hev-unsk.c
BUILD src/hev-xnsk.c
BUILD src/kern/aide/hev-task-aide.c
BUILD src/kern/io/hev-task-io-reactor-kqueue.c
BUILD src/kern/io/hev-task-io-reactor-epoll.c
BUILD src/kern/io/hev-task-io-reactor.c
BUILD src/kern/core/hev-task-system.c
BUILD src/kern/core/hev-task-system-schedule.c
BUILD src/kern/task/hev-task-executer.c
BUILD src/kern/task/hev-task.c
BUILD src/kern/task/hev-task-stack-mmap.c
BUILD src/kern/task/hev-task-stack-heap.c
BUILD src/kern/task/hev-task-call.c
BUILD src/kern/sync/hev-task-mutex.c
BUILD src/kern/sync/hev-task-cond.c
BUILD src/kern/itc/hev-task-channel-select.c
BUILD src/kern/itc/hev-task-channel.c
BUILD src/kern/time/hev-task-timer.c
BUILD src/kern/time/hev-task-timer-timerfd.c
BUILD src/kern/time/hev-task-timer-kevent.c
BUILD src/mem/simple/hev-memory-allocator-simple.c
BUILD src/mem/api/hev-memory-allocator-api.c
BUILD src/mem/base/hev-memory-allocator.c
BUILD src/mem/slice/hev-memory-allocator-slice.c
BUILD src/lib/rbtree/hev-rbtree-cached.c
BUILD src/lib/rbtree/hev-rbtree.c
BUILD src/lib/io/basic/hev-task-io.c
BUILD src/lib/io/poll/hev-task-io-poll.c
BUILD src/lib/io/pipe/hev-task-io-pipe.c
BUILD src/lib/io/buffer/hev-circular-buffer.c
BUILD src/lib/io/socket/hev-task-io-socket.c
BUILD src/lib/list/hev-list.c
BUILD src/lib/dns/hev-task-dns.c
BUILD src/lib/dns/hev-task-dns-proxy.c
BUILD src/lib/object/hev-object.c
BUILD src/lib/object/hev-object-atomic.c
BUILD src/lib/misc/hev-debugger.c
BUILD src/lib/cio/buffer/hev-task-cio-buffer.c
BUILD src/lib/cio/fd/hev-task-cio-fd.c
BUILD src/lib/cio/null/hev-task-cio-null.c
BUILD src/lib/cio/socket/hev-task-cio-socket.c
BUILD src/lib/cio/base/hev-task-cio.c
BUILD src/kern/task/hev-task-execute.S
LINK  bin/libhev-task-system.a
LINK  bin/natmap
STRIP bin/natmap
root@arm:/natmap_make/natmap-20240409-next# ./bin/natmap -s stunserver.stunprotocol.org -h example.com -b 29414 -i eth0
[E] stun_tcp src/hev-stun.c:131 STUN TCP recv failed.
[E] stun_bind src/hev-stun.c:259
[E] task_entry src/hev-stun.c:311
[E] stun_tcp src/hev-stun.c:131 STUN TCP recv failed.
[E] stun_bind src/hev-stun.c:259
[E] task_entry src/hev-stun.c:311

**Comment by heiher** [comment]
贴一下三方软件启动前后的各个网口配置、路由配置。

```sh
ifconfig
ip rule
ip route
```

**Comment by dmserver** [comment]
> 贴一下三方软件启动前后的各个网口配置、路由配置。
> 
> ```shell
> ifconfig
> ip rule
> ip route
> ```

重启主机就正常了

**Comment by dmserver** [comment]
> 贴一下三方软件启动前后的各个网口配置、路由配置。
> 
> ```shell
> ifconfig
> ip rule
> ip route
> ```

安装完那些组网软件 必须重启主机才行
