### ISSUE TITLE
请求在wireguard安卓客户端增加TXT记录解析

### ISSUE THREAD

**Issue by xf110** [heiher/natmap#63]
wireguard安卓客户端能直接解析IP4P很不错，但是在没有v6的环境中还需手动设置dns服务器为223.5.5.5，不方便。能不能在安卓客户端加入直接解析txt记录的功能？比如域名123.abc.com的txt记录为打洞获取的公网地址和端口123.45.23.66:7899  ，就像直接解析ip4p一个效果，这样无论在什么环境下都不用特殊设置。

**Comment by lmq8267** [comment]
设置dns也不行解析不了  参考这里 [ip4p存在的问题](https://www.bilibili.com/read/mobile?id=28934286) 帖子中标注的  不过确实txt记录更全面  通用性更强  ，通过ddns脚本 将生成的ip 端口 解析域名 就方便多了

**Comment by lmq8267** [comment]
#31

**Comment by heiher** [comment]
IP4P在一些操作系统上使用系统内置的DNS解析API的确会有依赖配置IPv6地址的问题，不过这可以换DNS解析实现来解决。

之前我是比较担心运营商的DNS服务器对TXT记录可能不会像A/AAAA记录那样进行友好的缓存，导致解析延迟会比较大。我这实测了一下TXT记录，运营商的DNS服务器有比较高的概率不返回结果，而AAAA记录则非常稳定。（不知道是不是个例

**Comment by lmq8267** [comment]
[这个组网插件](https://github.com/lbl8603/vnt/commit/12d4fc8e980067527f870916c656d8ecbb3984f5) 增加了txt域名地址   使用起来很方便   没有延迟的问题    将natmap生成的ip和端口  以IP:端口解析到域名的txt记录          这个插件就填写域名 就能链接到服务器了  很方便         所以很期望增加wireguardAPP的txt记录

**Comment by Caiminoyume** [comment]
DNS 已经存在指示 port 的SRV (type 64) 记录了，建议直接使用 SRV 记录

**Comment by AkashiCoin** [comment]
作为记录ip和端口，建议使用SRV记录更为合适

**Comment by heiher** [comment]
SRV要做两次解析，IP地址一次，端口一次。当初的考虑是倾向于只做一次解析，且缓存友好。

**Comment by dmserver** [comment]
https://cloud.tencent.com/document/product/302/12647
主机记录：服务的名字.协议的类型。例如，设置为 _sip._tcp。
记录类型：选择 “SRV”。
线路类型：选择 “默认” 类型，否则会导致部分用户无法解析。
记录值：优先级 权重 端口 主机名。记录生成后会自动在域名后面补一个 “.”。
例如，设置为 0 5 5060 sipserver.example.com。
MX 优先级：不需要填写。
TTL：为缓存时间，数值越小，修改记录各地生效时间越快，默认为600秒。
4. 单击确认，完成添加。

**Comment by dmserver** [comment]
https://cloud.tencent.com/document/product/302/12648


> SRV做两次解析，IP地址一次，端口一次。最初的考虑是倾向于只做一次解析，缓存方式，且客户端解析实现简单。

其实解析这个不需要担心，只要适配了，他们有办法去更新记录，如果可以的话 txt srv ip4p都有最好

**Comment by seanwang338** [comment]
附议，实测各种环境，TXT比IPV6解析适用性要好

**Comment by AkashiCoin** [comment]
> 应该可以通过下面的项目解决向客户端或对端共享/报告打洞后的出口IP地址及端口的问题，而且对脚本更友好 https://github.com/Violet-sword/Exchange-Variable

这种法子有点过于麻烦了，好的做法还是应该在dns上做解析而不是用第三方

**Comment by zhcode-fun** [comment]
可以试试我魔改的版本
https://github.com/zhcode-fun/wireguard-android

如果需要windows版本的，在这
https://github.com/zhcode-fun/wireguard-windows

**Comment by zhcode-fun** [comment]
> 大佬 可否改下这个[wg](https://github.com/WireGuard/wireguard-tools)工具

不好意思，我对 C 一窍不通

**Comment by zhcode-fun** [comment]
> 编译的时候 提示 WARNING: ./ui/build/intermediates/merged_java_res/googleplay/mergeGoogleplayJavaResource/base.jar: R8: Unexpected reference to missing service class: META-INF/services/java.net.spi.InetAddressResolverProvider.

我在README加了编译步骤，如果还有问题，在[wireguard-android/issues](https://github.com/zhcode-fun/wireguard-android/issues)里问吧

**Comment by xf110** [comment]
[wireguard (ip4p,txt,srv).zip](https://github.com/user-attachments/files/17182974/wireguard.ip4p.txt.srv.zip)
已经做出来了,支持ip4p,ipv6,txt,srv记录解析。感谢zhcode-fun
