### ISSUE TITLE
Does it support FreeBSD?

### ISSUE THREAD

**Issue by VaneHsiung** [heiher/natmap#66]
运行如下

```bash
$ sudo ./natmap -i re0  -s turn.cloudflare.com -h qq.com -b 54320
[E] hev_sock_client_tcp src/hev-sock.c:155
[E] tnsk_run src/hev-tnsk.c:107 Start TCP keep-alive service failed.

$ pystun3 -H stun.babelforce.com --debug -p 54320
...
NAT Type: Full Cone
...
```

**Comment by VaneHsiung** [comment]
```bash
$ ./natmap -4 -i re0 -s turn.cloudflare.com -h qq.com -b 54320 -t 127.0.0.1 -p 8096
[E] hev_sock_client_tcp src/hev-sock.c:155
[E] tnsk_run src/hev-tnsk.c:107 Start TCP keep-alive service failed.
```

**Comment by heiher** [comment]
FreeBSD暂不支持`-i`绑定网卡。

**Comment by MikeWang000000** [comment]
关于 `-i` ，我觉得可以像 curl 的  `--interface` 参数一样支持绑定 IP 地址：
https://github.com/curl/curl/blob/fd567d4f06857f4fc8e2f64ea727b1318f76ad33/lib/cf-socket.c#L401-L648

虽然绑定 IP 地址和绑定网络接口不大一样，但是绝大多数情况下是可以互相替代的，也能给一些暂不支持绑定网口的 OS 一种替代选择。
这种想法如何呢。

**Comment by heiher** [comment]
根据之前的经验，多网口多拨的场景才需要`-i`，如果是需要走非默认路由的网口，也没有根据源地址选择路由的高优先级路由规则（一般都没有），仅绑定IP地址是不行的。（我应该没有记错了吧

**Comment by MikeWang000000** [comment]
仅绑定 IP 地址是应该是有用的。

curl 做的比较直接，对所有不能使用 `SO_BINDTODEVICE` 的情形，都是将网络接口解析为 IP 地址，然后绑定的是 IP 地址。
具体可以参考我上面引用的代码。

毕竟不考虑多个网口IP地址相同这种古怪的情形，指定来源IP，流量也只能从那个IP的网口出，也就相当于绑定了网口了（

**Comment by heiher** [comment]
最初的实现就是绑定源地址的，群里有人报多wan口时IP会变的问题。刚也搜索了下群里的记录，是mwan3的情况绑定源地址无效，只能绑定设备才能锁定。对于一般场景绑定源地址应该是可行的，考虑加上。谢谢~
