### ISSUE TITLE
如何判断打洞成功

### ISSUE THREAD

**Issue by zzzzzhy** [heiher/natmap#69]
![image](https://github.com/heiher/natmap/assets/17536610/1a0b18ca-58ab-43ca-967c-996bb82ac0b0)
这样是打洞成功了吗,但是收不到udp信息

**Comment by heiher** [comment]
路由器上增加DMZ指向192.168.100.111。

**Comment by zzzzzhy** [comment]
![image](https://github.com/heiher/natmap/assets/17536610/aa9a1f67-cdaf-4f09-a703-59e081baa594)
![image](https://github.com/heiher/natmap/assets/17536610/53fbcb53-5475-41b0-9671-68dbf43d66d5)
还是一样

**Comment by heiher** [comment]
确认路由器和192.168.100.111主机的防火墙均允许UDP5600端口的入站。还不行可能就不是Full cone。

**Comment by zzzzzhy** [comment]
ok
