### ISSUE TITLE
unix socket支持

### ISSUE THREAD

**Issue by imzlh** [heiher/natmap#71]
我觉得吧，既然natmap只支持linux系统，何不使用高性能的unix domain socket(usd)呢
与nginx等支持usd通信应该会更快
不知道大大有没有这个计划

**Comment by heiher** [comment]
感觉没有必要使用Unix domain socket。对于natmap和服务端在同一主机的场景，首选[绑定模式](https://github.com/heiher/natmap?tab=readme-ov-file#bind-mode)，这样业务流量完全不经过natmap。

**Comment by imzlh** [comment]
我不是很理解这个-b参数，是需要reuseport然后natmap将这个端口暴露吗？
这个绑定模式原理可以讲一下吗
