### ISSUE TITLE
natmap能否实现从某一段端口中自动选择一个端口作为绑定的本地端口

### ISSUE THREAD

**Issue by doyoman** [heiher/natmap#73]
-b参数填0是随机端口，填指定端口是固定此端口，能否填一段端口，比如：-b 33333-33399  这样的话，可以每次从这一段里面第一个端口开始尝试打洞，如果失败了就尝试下一个端口，这样更便于写防火墙规则，同时又不至于因为端口导致打洞失败，

**Comment by dmserver** [comment]
你可以在启动程序上动手   由启动程序生成指定范围的随机端口 然后再启动natmap
我就是用的这种方法批量启动的natmap    然后设置指定时间 如果natmap没获取到ip信息 就kill掉进程再换端口启动

**Comment by heiher** [comment]
natmap不会支持单实例同时绑定映射多个端口，将 `-b <port>-<port>` 用于顺序分配源端口。
