### ISSUE TITLE
命令报错

### ISSUE THREAD

**Issue by lpdswing** [heiher/natmap#74]
./natmap -s stunserver.stunprotocol.org -h baidu.com -b 45678 
[E] hev_sock_client_stun src/hev-sock.c:304
[E] task_entry src/hev-stun.c:305 Start STUN service failed.

请问这是什么问题

**Comment by heiher** [comment]
原因：https://github.com/heiher/natmap/issues/18#issuecomment-2182097114
解决：`-s stunserver.stunprotocol.org` -> `-s turn.cloudflare.com`
