### ISSUE TITLE
打洞成功但无法访问

### ISSUE THREAD

**Issue by beck023** [heiher/natmap#77]
之前一直正常使用,某天突然频繁改变端口,差不多35秒就要变一次,PPPOE并没有掉线,外网IP也保持不变, 持续了大约一个小时,然后就好了,但是从此以后无法通过公网IP+端口访问了,但是打洞显示是成功的.
重新拨号和重启光猫也没用,我猜是不是运营商加了防火墙.
顺便问下,是不是只有NAT1才能打洞成功? 我本来怀疑是运营商给我从NAT1降到了NAT234,但是又显示打洞成功了.

**Comment by heiher** [comment]
natmap并没有入站可达性检测，正常输出公网地址和端口并不表明是NAT1。根据你的描述，NAT类型被运营商单方面修改的可能性很大，建议投诉要求恢复。

**Comment by beck023** [comment]
谢谢回复, PC上PPPOE拨号测了下NAT类型,果然变了,UDP 测出来是NAT3 ,TCP就直接失败了, 看来是运营商干的好事.

**Comment by heiher** [comment]
果断逐级投诉吧，我已经有成功恢复的好几个案例了，有耐心慢慢搞。
