### ISSUE TITLE
官方主分支编译的最新的natmap无法正常获取外部地址端口

### ISSUE THREAD

**Issue by ragingbulld** [heiher/natmap#78]
![image](https://github.com/user-attachments/assets/0a133ad7-de5a-4d42-8fd7-16bfb0133c6f)
![image](https://github.com/user-attachments/assets/8c809d35-07dc-427e-adc5-f6b147c1fda4)

**Comment by ragingbulld** [comment]
63的可以

**Comment by heiher** [comment]
好的，感谢反馈，晚点我看看。

**Comment by heiher** [comment]
问题正在修复中： https://github.com/openwrt/packages/pull/24812

**Comment by heiher** [comment]
snapshot & 23.05 已修复。
