### ISSUE TITLE
发现一个可以部署在CF workers上的项目能够向客户端或对端共享/报告打洞后的出口IP地址及端口

### ISSUE THREAD

**Issue by egg1234** [heiher/natmap#81]
项目地址，只需要粘贴代码到workers里面即可
https://github.com/Violet-sword/Exchange-Variable

内网设备打洞后得到的公网IP地址及端口可以用下面命令存储到CF workers上
curl https://your-name.workers.dev/?stored-text=8.8.8.8:1000

客户端或对端使用下面命令得到当前内网设备打洞后的公网IP地址及端口
curl https://your-name.workers.dev

以上操作也可完全在浏览器上进行

当然基于国内的情况，workers需要自定义域名访问

**Comment by HSXX** [comment]
也可以用php做
`    <?php
    // 设置数据库文件路径
    $dbFile = __DIR__ . '/data.db';
     
    // 创建一个新的PDO实例连接到SQLite数据库
    try {
        $pdo = new PDO("sqlite:$dbFile");
        // 设置错误模式为异常
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
     
        // 创建表（如果不存在）
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS key_value_store (
                id TEXT PRIMARY KEY,
                value TEXT
            )
        ");
    } catch (PDOException $e) {
        die("数据库连接失败: " . $e->getMessage());
    }
     
    // 检查请求方法
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        // 处理POST请求，保存键值对
        $id = isset($_POST['id']) ? $_POST['id'] : null;
        $value = isset($_POST['value']) ? $_POST['value'] : null;
     
        if ($id && $value) {
            try {
                // 插入或更新数据
                $stmt = $pdo->prepare('INSERT OR REPLACE INTO key_value_store (id, value) VALUES (:id, :value)');
                $stmt->execute([':id' => $id, ':value' => $value]);
                echo "键值对 {$id}={$value} 已保存";
            } catch (PDOException $e) {
                echo "数据库操作失败: " . $e->getMessage();
            }
        } else {
            echo "缺少必要的参数:id 和 value";
        }
    } elseif ($_SERVER['REQUEST_METHOD'] === 'GET') {
        // 处理GET请求，查询键值对
        $id = isset($_GET['id']) ? $_GET['id'] : null;
     
        if ($id) {
            try {
                $stmt = $pdo->prepare('SELECT value FROM key_value_store WHERE id = :id');
                $stmt->execute([':id' => $id]);
                $result = $stmt->fetch(PDO::FETCH_ASSOC);
     
                if ($result) {
                    echo $result['value'];
                } else {
                    echo "未找到ID {$id}";
                }
            } catch (PDOException $e) {
                echo "数据库操作失败: " . $e->getMessage();
            }
        } else {
            echo "缺少必要的参数:id";
        }
    } else {
        // 不支持的方法
        http_response_code(405);
        echo "不支持的请求方法";
    }
    ?>`

**Comment by lalasou** [comment]
`addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request));
});

// Define the KV namespace key and content key for easy updates
const KV_NAMESPACE = TEXT_CONTENT;  // Replace 'TEXT_CONTENT' with your desired KV namespace
const CONTENT_KEY = 'currentText';   // The key used for storing/retrieving content in KV

// Function to generate common response headers
function getResponseHeaders() {
  return {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'text/plain'
  };
}

async function handleRequest(request) {
  const url = new URL(request.url);

  if (request.method === 'OPTIONS') {
      // Handle CORS preflight request
      return new Response(null, {
          status: 204,
          headers: {
              'Access-Control-Allow-Origin': '*',
              'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
              'Access-Control-Allow-Headers': 'Content-Type'
          }
      });
  }

  const urlParam = url.searchParams.get('stored-text');  // Check for the 'stored-text' parameter

  if (urlParam) {
      // Update content if 'stored-text' parameter is present
      try {
          await KV_NAMESPACE.put(CONTENT_KEY, urlParam);  // Store the new value in KV
          return new Response(urlParam, {
              status: 200,
              headers: getResponseHeaders()
          });
      } catch (err) {
          console.error('Failed to update content:', err);  // Log the error
          return new Response('Failed to update content', {
              status: 500,
              headers: { 'Access-Control-Allow-Origin': '*' }
          });
      }
  } else {
      // Fetch and return content if no 'stored-text' parameter is present
      try {
          const currentText = await KV_NAMESPACE.get(CONTENT_KEY) || 'Hello World';  // Fallback to 'Hello World'
          return new Response(null, {
            status: 302,
            headers: {
                'Location': currentText,
                'Access-Control-Allow-Origin': '*',
                'Content-Type': 'text/html; charset=UTF-8'
            }
          });
      } catch (err) {
          console.error('Failed to retrieve content:', err);  // Log the error
          return new Response('Failed to retrieve content', {
              status: 500,
              headers: { 'Access-Control-Allow-Origin': '*' }
          });
      }
  }
}`
