### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by dmserver** [heiher/natmap#82]
打洞网页后   网页服务端无法识别到访问者的真实IP
后端唯一能获取到的ip只有natmap软件所在机器的访问ip

比如访问用户ip是1.1.1.1
natmap本地是192.168.6.1
web后端是192.168.6.7

需要web后端获取识别到用户的1.1.1.1  但实际上获取的始终是192.168.6.1

不知道这个问题怎么解决

理论上来说tcp转发应该可以识别到才是啊  目前唯一能知道的是  cloudflare 进行代理后 web后端是能识别到用户IP的 但需要自行识别
因为默认识别头还是192.168.6.1 但是在信息里面可以看到附加了用户的真实IP

雷池waf有下面这些参数 可以让后端获取到真实IP   但是natmap不知道怎么搞
代理时修改请求中的 Host 头
$http_host
Host 头
为上游服务器传递 X-Forwarded-Host、 X-Forwarded-Proto
代理时增加 X-Forwarded-Host、X-Forwarded-Proto 头
清空并重写 X-Forwarded-For
雷池部署在最外层时，重写 XFF 可以避免客户端伪造 IP

**Comment by heiher** [comment]
使用绑定模式加防火墙转发即可。
