### ISSUE TITLE
Action 编译的最新的natmap IPV4 正常 V6 不对

### ISSUE THREAD

**Issue by zuozhehao** [heiher/natmap#84]
<img width="804" alt="image" src="https://github.com/user-attachments/assets/311079ea-7270-4423-a6d7-194005d56615">

**Comment by zuozhehao** [comment]
@heiher 目前是使用域名。如何支持V4和V6 都可以正常转发。

**Comment by heiher** [comment]
没有公网IP的话，最好分为两个域名。如果使用IP4P的方案，一个域名也不是不行，但两条AAAA解析记录还是和典型的A、AAAA记录方式不同。

**Comment by zuozhehao** [comment]
> 没有公网IP的话，最好分为两个域名。如果使用IP4P的方案，一个域名也不是不行，但两条AAAA解析记录还是和典型的A、AAAA记录方式不同。

@heiher 都有公网IP的。内网设备只能分配V4，又需要支持V6通信。

**Comment by heiher** [comment]
这样就是变成一个纯转发器，理论上可以的。但是这种需求使用防火墙转发效率会更高。
