### ISSUE TITLE
Mac打洞如何访问

### ISSUE THREAD

**Issue by zscorpio** [heiher/natmap#87]
你好 我想先测试一下, 我用了surge ponte, 是可以打洞成功的, 所以我怀疑我应该是 full cone 的.
mac mini上安装了natmap(编译安装)
首先启动一个http的服务, 
```shell
python3 -m http.server 18082
Serving HTTP on :: port 18082 (http://[::]:18082/) ...
``` 
然后执行natmap
```shell
 ./natmap -s turn.cloudflare.com -h qq.com -b 7124 -t 192.168.6.40 -p 18082
60.249.39.31 40620 2001::9eac:3cf9:271f 7124 tcp 198.18.0.1
``` 

想问问这个时候我想通过浏览器里面, ip+port访问, 是应该怎么访问, 这个是否支持

**Comment by heiher** [comment]
这是透过代理吗？试试访问 60.249.39.31:40620 ，如果不行看看是不是哪一层防火墙没有允许入站，也可能是代理不支持TCP的Full cone，一般大概率是这样的。

**Comment by zscorpio** [comment]
-> # ./gostun
 WARNING: 2024/12/26 10:27:04 NAT mapping behavior: inconclusive
 WARNING: 2024/12/26 10:27:06 => NAT filtering behavior: endpoint independent
 WARNING: 2024/12/26 10:27:06 => NAT mapping behavior: address dependent
 WARNING: 2024/12/26 10:27:06 => NAT filtering behavior: endpoint independent
NAT Type: address dependent[NatMappingBehavior] endpoint independent[NatFilteringBehavior]

我用gostun测试了一下是这样的

**Comment by zscorpio** [comment]
你这么一说, 我这个情况可能比较特殊, 我详细描述一下哈

```shell
光猫拨号(192.168.1.1) => 主路由器(192.168.1.2, 192,168.6.1) => mac mini(192.168.6.40, 安装了surge)
``` 
光猫设置了DMZ是主路由192.168.1.2   主路由上设置了DMZ是192.168.6.40
我试过了, 光猫设置其他ip, 手机上surge ponte连不回家, 当前设置, 是可以回家的, 所以我怀疑是full cone, 用好多工具测试过, 但是结果都不太一样...

上面你说的那个端口 60.249.39.31:40620, 我测试过了, 不能访问, 不过我检查过光猫上防火墙开的, mac也是开的, 难道主路由也有防火墙么?

我晚上到时候macbook直连光猫wifi测试看看, 先简化网络

**Comment by heiher** [comment]
如果TCP是NAT1，两层路由都配了DMZ的话应该只要mac防火墙放行就可以的。需要注意TCP和UDP的NAT是分开的，gostun测的是TCP还是UDP？

**Comment by zscorpio** [comment]
gostun好像是udp

**Comment by zscorpio** [comment]
找到原因啦...但是不知道怎么解决
昨晚我用另外一台mac, 直接连接光猫的wifi, 是可以通的. 然后我把光猫设置为桥接, 路由器拨号, DMZ设置为mac mini
光猫桥接(192.168.1.1) => 主路由器拨号(192.168.1.2, 192,168.6.1) => mac mini(192.168.6.40, 安装了surge)
我把surge关闭的情况, 可以正常打洞, (一开始还有一个坑, 是stun server走代理了, 后来换成直连), 外网可以正常访问
surge打开的情况下, 就不能正常访问了, 好像说是端口转发问题, 不过我不知道咋处理了...

**Comment by heiher** [comment]
surge打开的话，对系统网络有什么影响？

**Comment by zscorpio** [comment]
哈哈哈, 我也说不来, 反正不是你的这个的 bug, 我先关闭, 感谢!
我去 surge 论坛上看过, 大概是说路由器转发的时候, 可能没带原始 ip 啥的

**Comment by heiher** [comment]
跑在拨号路由上比较简单，即使是多拨也可以绑定网口。

**Comment by zscorpio** [comment]
嗯, 我主路由是TL-R479GP-AC, 放在入口处,  这个好像不支持跑程序, 感觉 openwrt 之类怕不稳定
